# Generated by Django 6.0.7 on 2026-07-31 06:01

from django.db import migrations
from django.contrib.auth.hashers import make_password


def create_default_admin(apps, schema_editor):
    Registration = apps.get_model('myapp', 'Registration')

    if not Registration.objects.filter(username='admin').exists():
        Registration.objects.create(
            username='admin',
            email='admin@library.com',
            password=make_password('admin123'),
            mobile='9999999999',
            gender='male',
            address='Library Admin Office',
            is_admin=True,
        )


def remove_default_admin(apps, schema_editor):
    Registration = apps.get_model('myapp', 'Registration')
    Registration.objects.filter(username='admin', is_admin=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_book_image_registration_is_admin'),
    ]

    operations = [
        migrations.RunPython(create_default_admin, remove_default_admin),
    ]
